name: Dev Branch Pipeline
 
on:
  push:
    branches:
      - dev
  workflow_dispatch:
 
jobs:
  say-hello-dev:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Echo Dev Message
        run: echo "hello this is the dev branch"
